management:
  info: # 애플리케이션 정보
    java:
      enabled: true
    os:
      enabled: true
    env: # info 하위에 설정을 드러냄
      enabled: true
  server:
    port: 8080
  endpoint: # 개별 속성 detail
    shutdown:
      enabled: true # 활성화
    health:
      show-components: always
      #show-details: always
  endpoints:
    web:
      exposure:
        include: "*" # 기능 노출
        # exclude: "env, bean"

info:
  app:
    name: hello-actuator
    company: yh

logging:
  level:
    hello.controller: debug

server:
  tomcat:
    mbeanregistry:
      enabled: true