management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude:
          - beans
          - quartz
      cors:
        allowed-origins: https://test.com
        allowed-methods: GET

#  endpoint:
#    shutdown:
#      enabled: true
#      cache:
#        time-to-live: 10s
#    beans:
#      enabled: false
#    health:
#      enabled: true
#      cache:
#        time-to-live: 1d
#    caches:
#      enabled: true
#    loggers:
#      enabled: true
#    quartz:
#      enabled: false
